name: Setup
description: "Setup the environment"

runs:
  using: "composite"
  steps:
    # Setup the SDKs
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Setup JDK
      uses: actions/setup-java@v5
      with:
        distribution: zulu
        java-version: '21'
        cache: 'gradle'
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        packages: "tools platform-tools build-tools;36.0.0 ndk;29.0.14206865"
    - name: Add NDK to path
      shell: bash
      run: |
        echo "Adding to path: ${{ env.ANDROID_SDK_ROOT }}/ndk/29.0.14206865:${{ env.ANDROID_SDK_ROOT }}/ndk/29.0.14206865/toolchains/llvm/prebuilt/linux-x86_64/bin"
        echo "${{ env.ANDROID_SDK_ROOT }}/ndk/29.0.14206865:${{ env.ANDROID_SDK_ROOT }}/ndk/29.0.14206865/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH
